[[headers]]
  for = "/*"
  [headers.values]
    ACCESS-CONTROL-ALLOW-ORIGIN = "*"
[build]
  publish = "build"
  command = "npm run build:netlify"
[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_ERKENNINGEN_GRAPHQL_API_URL = "https://api.aockeurmerk.nl/graphql"
  REACT_APP_ERKENNINGEN_ADMIN_URL = "https://aockeurmerk.nl"
  REACT_APP_ERKENNINGEN_SITE_TYPE = "administratie"
  GASTBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.aockeurmerk.nl/graphql"
  GASTBY_ERKENNINGEN_ADMIN_URL = "https://aockeurmerk.nl"
  GASTBY_ERKENNINGEN_SITE_TYPE = "administratie"
[context.acceptance.environment]
  NODE_ENV = "production"
  REACT_APP_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.aockeurmerk.nl/graphql"
  REACT_APP_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.aockeurmerk.nl"
  REACT_APP_ERKENNINGEN_SITE_TYPE = "administratie"
  GASTBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.aockeurmerk.nl/graphql"
  GASTBY_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.aockeurmerk.nl"
  GASTBY_ERKENNINGEN_SITE_TYPE = "administratie"
[context.deploy-preview.environment]
  NODE_ENV = "production"
  REACT_APP_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.aockeurmerk.nl/graphql"
  REACT_APP_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.aockeurmerk.nl"
  REACT_APP_ERKENNINGEN_SITE_TYPE = "administratie"
  GASTBY_ERKENNINGEN_GRAPHQL_API_URL = "https://api.acceptatie.aockeurmerk.nl/graphql"
  GASTBY_ERKENNINGEN_ADMIN_URL = "https://administratie.acceptatie.aockeurmerk.nl"
  GASTBY_ERKENNINGEN_SITE_TYPE = "administratie"  